const SearchActionsConstants = {
  SEARCH_LOAD: "SEARCH_LOAD",
  SEARCH_LOAD_SUCC: "SEARCH_LOAD_SUCC",
  SEARCH_LOAD_FAIL: "SEARCH_LOAD_FAIL",
  SEARCH_KEY_CHNGE: "SEARCH_KEY_CHNGE",
  SEARCH_SELECT_CHNGE: "SEARCH_SELECT_CHNGE",
  SEARCH_KEY_LOCATION_CHNGE: "SEARCH_KEY_LOCATION_CHNGE",
  SEARCH_STAR_CHNGE: "SEARCH_STAR_CHNGE",
  SEARCH_TOPIC_CHNGE: "SEARCH_TOPIC_CHNGE",
  SEARCH_SORT_CHNGE: "SEARCH_SORT_CHNGE",
  SEARCH_DAYS_FILTER_CHNGE: "SEARCH_DAYS_FILTER_CHNGE",
  SEARCH_SCALE_CHNGE: "SEARCH_SCALE_CHNGE"
};

export { SearchActionsConstants };
