const UserEditActionsConstants = {
  USER_EDIT_REQ: "USER_EDIT_REQ",
  USER_EDIT_SUCC: "USER_EDIT_SUCC",
  USER_EDIT_FAIL: "USER_EDIT_FAIL",
  USER_EDIT_USER_CHNGE: "USER_EDIT_USER_CHNGE",
  USER_EDIT_LOCT_CHNGE: "USER_EDIT_LOCT_CHNGE",
  USER_EDIT_PICT_CHNGE: "USER_EDIT_PICT_CHNGE",
  USER_EDIT_USER_VALIDATE: "USER_EDIT_USER_VALIDATE",
  USER_EDIT_USER_VALIDATE_SUCC: "USER_EDIT_USER_VALIDATE_SUCC",
  USER_EDIT_USER_VALIDATE_FAIL: "USER_EDIT_USER_VALIDATE_FAIL",
  USER_EDIT_LOAD_USER: "USER_EDIT_LOAD_USER",
  USER_EDIT_LOAD_USER_SUCC: "USER_EDIT_LOAD_USER_SUCC",
  USER_EDIT_LOAD_USER_FAIL: "USER_EDIT_LOAD_USER_FAIL",
  USER_EDIT_MODAL_OPEN: "USER_EDIT_MODAL_OPEN",
  USER_EDIT_MODAL_CLOSE: "USER_EDIT_MODAL_CLOSE"
};

export { UserEditActionsConstants };
