const RegisterActionsConstants = {
  REGISTER_REQ: "REGISTER_REQ",
  REGISTER_SUCC: "REGISTER_SUCC",
  REGISTER_FAIL: "REGISTER_FAIL",
  REGISTER_USER_CHNGE: "REGISTER_USER_CHNGE",
  REGISTER_LOCT_CHNGE: "REGISTER_LOCT_CHNGE",
  REGISTER_PICT_CHNGE: "REGISTER_PICT_CHNGE",
  REGISTER_USER_VALIDATE: "REGISTER_USER_VALIDATE",
  REGISTER_USER_VALIDATE_SUCC: "REGISTER_USER_VALIDATE_SUCC",
  REGISTER_USER_VALIDATE_FAIL: "REGISTER_USER_VALIDATE_FAIL",
  MODAL_OPEN: "MODAL_OPEN",
  MODAL_CLOSE: "MODAL_CLOSE"
};

export { RegisterActionsConstants };
