const LoginActionsConstants = {
  LOGIN_REQ: "LOGIN_REQ",
  LOGOUT_REQ: "LOGOUT_REQ",
  LOGIN_REQ_SUCC: "LOGIN_REQ_SUCC",
  LOGOUT_REQ_FAIL: "LOGOUT_REQ_FAIL",
  LOGOUT_REQ_SUCC: "LOGOUT_REQ_SUCC",
  LOGIN_USER_CHNGE: "LOGIN_USER_CHNGE",
  LOGIN_REQ_FAIL: "LOGIN_REQ_FAIL"
};

export { LoginActionsConstants };
