const ReviewViewActionsConstants = {
  REVIEW_VIEW_LOAD: "REVIEW_VIEW_LOAD",
  REVIEW_VIEW_LOAD_SUCC: "REVIEW_VIEW_LOAD_SUCC",
  REVIEW_VIEW_LOAD_FAIL: "REVIEW_VIEW_LOAD_FAIL",
  REVIEW_VIEW_KEY_CHNGE: "EARCH_KEY_CHNGE",
  REVIEW_VIEW_SELECT_CHNGE: "REVIEW_VIEW_SELECT_CHNGE",
  REVIEW_VIEW_UNMINI: "REVIEW_VIEW_UNMINI",
  REVIEW_VIEW_MINI: "REVIEW_VIEW_MINI"
};

export { ReviewViewActionsConstants };
