const ReviewEditActionsConstants = {
  REVIEW_EDIT_REQ: "REVIEW_EDIT_REQ",
  REVIEW_EDIT_REQ_SUCC: "REVIEW_EDIT_REQ_SUCC",
  REVIEW_EDIT_REQ_FAIL: "REVIEW_EDIT_REQ_FAIL",
  REVIEW_EDIT_STAR_CHNGE: "REVIEW_EDIT_STAR_CHNGE",
  REVIEW_EDIT_PICT_SET: "REVIEW_EDIT_PICT_SET",
  REVIEW_EDIT_PICT_ADD: "REVIEW_EDIT_PICT_ADD",
  REVIEW_EDIT_LOAD: "REVIEW_EDIT_LOAD",
  REVIEW_EDIT_LOAD_SUCC: "REVIEW_EDIT_LOAD_SUCC",
  REVIEW_EDIT_LOAD_FAIL: "REVIEW_EDIT_LOAD_FAIL",
  REVIEW_EDIT_MAXIM: "REVIEW_EDIT_MAXIM",
  REVIEW_EDIT_MINIM: "REVIEW_EDIT_MINIM",
  REVIEW_EDIT_DELETE: "REVIEW_EDIT_DELETE",
  REVIEW_EDIT_DELETE_SUCC: "REVIEW_EDIT_DELETE_SUCC",
  REVIEW_EDIT_DELETE_FAIL: "REVIEW_EDIT_DELETE_FAIL"
};

export { ReviewEditActionsConstants };
