const RestaurantViewActionsConstants = {
  REST_VIEW_UNMINI: "REST_VIEW_UNMINI",
  REST_VIEW_MINI: "REST_VIEW_MINI",
  REST_VIEW_REVIEW_SHOW: "REST_VIEW_REVIEW_SHOW",
  REST_VIEW_REVIEW_HIDE: "REST_VIEW_REVIEW_HIDE",
  REST_VIEW_SORT_CHNGE: "REST_VIEW_SORT_CHNGE",
  REST_VIEW_SORT_TIME_CHNGE: "REST_VIEW_SORT_TIME_CHNGE",
  REST_VIEW_TOPIC_CHNGE: "REST_VIEW_TOPIC_CHNGE",
  REST_VIEW_STAR_CHNGE: "REST_VIEW_STAR_CHNGE",
  REST_VIEW_DAYS_FILTER_CHNGE: "REST_VIEW_DAYS_FILTER_CHNGE"
};

export { RestaurantViewActionsConstants };
