const RestaurantActionsConstants = {
  RESTAURANT_REQ: "RESTAURANT_REQ",
  RESTAURANT_REQ_SUCC: "RESTAURANT_REQ_SUCC",
  RESTAURANT_REQ_FAIL: "RESTAURANT_REQ_FAIL",
  RESTAURANT_NAME_CHNGE: "RESTAURANT_NAME_CHNGE",
  RESTAURANT_LOCT_CHNGE: "RESTAURANT_LOCT_CHNGE",
  RESTAURANT_INFO_CHNGE: "RESTAURANT_INFO_CHNGE"
};

export { RestaurantActionsConstants };
